### ISSUE TITLE
Preference to specify style

### ISSUE THREAD

**Issue by bwiernik** [dcartertod/zotero-plugins#1]
A user on the Zotero forums pointed out that if the default quick copy style has no bibliography, no preview is generated. It would be nice if there were a preference to specify a style to override the default style for such cases.

**Comment by dcartertod** [comment]
Thanks for letting me know! I'll have to research it.

**Comment by bwiernik** [comment]
Looking at the Zutilo plugin's Quick Copy code might be a good start.

**Comment by dcartertod** [comment]
Added in new release

**Comment by bwiernik** [comment]
Awesome!
