### ISSUE TITLE
Unable to intall ZoteroPreview for Zotero v. 5.0.96.3

### ISSUE THREAD

**Issue by mapfiable** [dcartertod/zotero-plugins#10]
When I try to install the plugin, I get the following error message:

`The add-on "%S" could not be installed. It may be incompatible with this version of Zotero.`

**Comment by dcartertod** [comment]
Which .xpi file are you installing?

**Comment by mapfiable** [comment]
The one in the main folder with the comment " New version...maybe".

**Comment by mapfiable** [comment]
Windows 10 Home. But nevermind that--I just tried the version on your [release page](https://github.com/dcartertod/zotero-plugins/releases/tag/0.0.7) and it works! Are they different?

**Comment by dcartertod** [comment]
They shouldn't be, but I do find github a bit mysterious sometimes.

**Comment by mapfiable** [comment]
Haha, I understand. Thanks!
