### ISSUE TITLE
The plugin is not working with the new Zotero 6.0-beta 

### ISSUE THREAD

**Issue by WMAM** [dcartertod/zotero-plugins#11]
As far as I understand, most plugins are affected. Here are more details:

https://forums.zotero.org/discussion/94418/6-0-beta-plugins-cannot-be-installed

It seems the manifest should be updated to be compatible with the new v6.0-beta:

![imagen](https://user-images.githubusercontent.com/31582800/153271299-16dbbec9-885d-43d2-9b3a-735d5e44b70d.png)

**Comment by dcartertod** [comment]
Done. Should be available now. Also validated on 6.0 as working :-)

**Comment by WMAM** [comment]
Yes, it is working for me also. Thank you so much!
