### ISSUE TITLE
The plugin is incompatible with the latest beta release of Zotero

### ISSUE THREAD

**Issue by MSBack** [dcartertod/zotero-plugins#12]
See https://github.com/ethanwillis/zotero-scihub/issues/67 for details.

**Comment by dcartertod** [comment]
Check for updates. I thought I'd already addressed this.

**Comment by madturtles** [comment]
The current code looks OK, but the latest release doesn't. Maybe it's time to publish a new one?

**Comment by MSBack** [comment]
Yeah, the current release doesn't have the fix.

**Comment by dcartertod** [comment]
Will review

**Comment by dcartertod** [comment]
Should be done

**Comment by dcartertod** [comment]
Updated Releases
