### ISSUE TITLE
preview pdf

### ISSUE THREAD

**Issue by wilson668** [dcartertod/zotero-plugins#16]
Is it possible to preview pdf

**Comment by S-Kee** [comment]
![image](https://user-images.githubusercontent.com/21167731/167570663-3125aab8-e7cf-45bf-8170-477581f67fff.png)

like this

**Comment by S-Kee** [comment]
> 

big lift? I don’t understand. The sidebar is like endnote. It is useful.

**Comment by wilson668** [comment]
> ![image](https://user-images.githubusercontent.com/21167731/167570663-3125aab8-e7cf-45bf-8170-477581f67fff.png)
> 
> like this

yeah, could you tell me how did you achieve it?

**Comment by S-Kee** [comment]
@wilson668 I achieve it by picture stitching. It is just a picture.

**Comment by tangjyan** [comment]
https://github.com/windingwind/zotero-pdf-preview
![teaser](https://user-images.githubusercontent.com/21167731/179129649-276d0f76-781a-4c50-be4d-115a4bfea766.gif)

**Comment by dcartertod** [comment]
Excellent. Very cool.
