### ISSUE TITLE
Choose Preview options don't stick

### ISSUE THREAD

**Issue by kerim** [dcartertod/zotero-plugins#20]
It won't let me change the preview style. Whenever I close the "chose preview style" window it reverts back to the previous setting.

**Comment by kerim** [comment]
I'm not seeing the OK button. That must be the problem. I'll see if I can find it by hunt-and-peck. Must be an issue with how things display on a Mac?

**Comment by kerim** [comment]
This is what I see: 
<img width="495" alt="Screen Shot 2022-07-19 at 7 25 11 AM" src="https://user-images.githubusercontent.com/59976/179647284-ca105d4d-6dc0-43e7-acef-f1416c6358bb.png">

**Comment by dcartertod** [comment]
I've heard of this happening on MacOS, but don't have access to one to test and troubleshoot.

However, I think I have a solution where making a selection and closing will retain that new selection.

**Comment by dcartertod** [comment]
Check for updates. Should be fixed.

**Comment by kerim** [comment]
Works now. Thanks!
