### ISSUE TITLE
Conflict with new PDF Preview plugin

### ISSUE THREAD

**Issue by mjthoraval** [dcartertod/zotero-plugins#22]
This plugin breaks when used together with the new plugin [PDF Preview](https://github.com/windingwind/zotero-pdf-preview) by windingwind.
When the two plugins are enabled, the Citation Preview does not update anymore.
You need to click on the PDF Preview tab and then go back to the Citation Preview tab to get the citation preview updated.
Tested on Windows 10, Zotero 6.0.14-beta.1+79246196a

**Comment by windingwind** [comment]
Hi, I just checked the code and find this to be a possible cause:
https://github.com/dcartertod/zotero-plugins/blob/be033feb3fac8163d6e4e3eda604f78613a758d5/ZoteroPreview/chrome/content/zoteropreview.js#L96

Please do not use the index `4` to locate the tab panel. Please check the tab element's `selected` attribute instead. See https://docs.huihoo.com/xul/xul-element-reference/ref_tab.html

**Comment by dcartertod** [comment]
Thank you for such a detailed issue! Should be resolved.
