### ISSUE TITLE
Unable to find ZoteroPreview.xpi

### ISSUE THREAD

**Issue by FalloutCrew** [dcartertod/zotero-plugins#24]
The readme installation instruction is to begin by downloading ZoteroPreview.xpi . However, I am unable to locate this file in this rep. 
Is the file renamed? A clarification would be useful.

**Comment by FalloutCrew** [comment]
Ah, thanks a lot. 
I found the link originally, but Firefox gave me an error message. I realize it probably thought it was a firefox extension.

**Comment by mjthoraval** [comment]
I have seen a warning from another Zotero add-on:

> NOTE for Firefox users: Firefox treats .xpi files as Firefox add-ons and tries to install them. Rather than clicking on the .xpi file, you can try right-clicking and choosing to save the link as a file. In some cases (particularly on Linux), Firefox does not allow right-clicking and saving the .xpi link either. In that case, you must download it either with a different browser or with a command-line tool like curl or wget.

https://github.com/wshanks/Zutilo/

I don't remember if they have such warning on the Zotero website.

**Comment by FalloutCrew** [comment]
Thanks a lot. Sorry for being a noob :)

tir. 18. okt. 2022 kl. 17:08 skrev Marie-Jean Thoraval <
***@***.***>:
