### ISSUE TITLE
local language

### ISSUE THREAD

**Issue by jlu511** [dcartertod/zotero-plugins#32]
Please add local language for zh cn.  or provide an english local language model for translation. thank you. 
![image](https://github.com/dcartertod/zotero-plugins/assets/64378673/58abd642-20f7-40ce-9b21-689e3f53b39a)
![image](https://github.com/dcartertod/zotero-plugins/assets/64378673/2495e224-f982-4027-9844-d5f8d0ebe524)

**Comment by dcartertod** [comment]
Will do. Absolutely. That was my next priority. Thank you for the reminder.

**Comment by dcartertod** [comment]
Added.  See

ZoteroPreview7/locale/zh-CN

**Comment by jlu511** [comment]
thank you very much

**Comment by jlu511** [comment]
I have corrected the translation based on Chinese expression habits.
![image](https://github.com/dcartertod/zotero-plugins/assets/64378673/75fc2865-8980-4ca2-9184-fc420d768bf8)
[zotero-preview.zip](https://github.com/dcartertod/zotero-plugins/files/14518147/zotero-preview.zip)
Attached is the file that I have modified

**Comment by dcartertod** [comment]
Done. Thank you very much for your contribution.
