### ISSUE TITLE
Abstract Cleaner update

### ISSUE THREAD

**Issue by dcartertod** [dcartertod/zotero-plugins#33]
Hi, I hope the defense went well; I hate to bother but is the Abstract Cleaner also coming?

_Originally posted by @7596ff in https://github.com/dcartertod/zotero-plugins/issues/26#issuecomment-2048755381_

**Comment by dcartertod** [comment]
> Hi, I hope the defense went well; I hate to bother but is the Abstract Cleaner also coming?

It did, thank you! 

I had no idea anyone was actually using the Abstract Cleaner, nor that it might be necessary anymore. I'll look into it.

**Comment by go-zhao** [comment]
Zotero Abstract Cleaner is a amzing plugins in zotero. it works well on z6.
Do you happen to have time to update it to Zotero 7. Thanks a lot!

**Comment by dcartertod** [comment]
Released Abstract Cleaner for version 7. Seems to work! :-)
