### ISSUE TITLE
Suggestion: entries in "Display" can be accurately searched in the search box of Zotero.

### ISSUE THREAD

**Issue by groele** [dcartertod/zotero-plugins#34]
Dear Developer,

Thank you very much for developing this plugin. It has had a significant impact on my studies and daily life. I am very grateful.

During my use, I have encountered some issues that I would like to share with you. When using Preview, I often use "temporary placeholders" while writing articles. However, when inserting references, I use these "temporary placeholders" to search for entries in Zotero to trace the original entries. The problem arises because the search results are not always unique, as shown in the attached image.

I hope you can optimize this feature. Below is a comparison image between [Better BibTeX for Zotero](https://retorque.re/zotero-better-bibtex/index.html) and Preview, as shown.

I hope that the entries in "Display" can be accurately searched in the search box of Zotero.
Thank you very much!

Best regards,
![图片1](https://github.com/dcartertod/zotero-plugins/assets/49476682/0f3a7a25-89c6-42d9-9749-76bfb27f40db)

**Comment by dcartertod** [comment]
I'm not this is possible
