### ISSUE TITLE
"not found" link

### ISSUE THREAD

**Issue by notuntoward** [dcartertod/zotero-plugins#36]
If I click on the link in the chunk of the README below, I get a "not found" message.

> For Zotero 7
> There's [a new version for Zotero 7](https://github.com/dcartertod/zotero-plugins/ZoteroAbstractCleaner7.xpi) only.

**Comment by dcartertod** [comment]
Fixed

**Comment by notuntoward** [comment]
Thanks.  I just tried the newly working link, but it points to a page containing ZoteroPreview7.xpi.  Shouldn't it be pointing to a .xpi file for Zotero Abstract Cleaner ?

**Comment by dcartertod** [comment]
Sorry, I misunderstood. Will review.

**Comment by dcartertod** [comment]
try now

**Comment by notuntoward** [comment]
It works.  Thanks!
