### ISSUE TITLE
Errors about font size and emoji

### ISSUE THREAD

**Issue by tomorrow-today** [dcartertod/zotero-plugins#37]
<img width="348" alt="image" src="https://github.com/user-attachments/assets/8b4e7eb4-1371-444a-9845-e7ba5f0cb943">
The font size is so big and cannot be changed. I find this error not exsit in my collegue's UI (both using MacOS).
Besides, the 'paste' emoji are in wrong places.

**Comment by dcartertod** [comment]
Have you tried changing the font size in the settings?
![image](https://github.com/user-attachments/assets/424a80d1-c06c-4f93-b3e8-378317c35fc4)

**Comment by fflamerie** [comment]
I face the same problem with font size. The "Spacing and size" section is not displayed in the settings. I have Zotero 7.0.3. Thank youf or this great plugin and thanks for your help.
![zotero_preview_settings](https://github.com/user-attachments/assets/28822f5e-ce53-4c45-bda2-3d09f9956838)

**Comment by dcartertod** [comment]
Interesting. I am assuming you have the latest version? 0.7.8

Have you picked a preview style? Not sure that that should make a difference, but just wondering.

**Comment by fflamerie** [comment]
Sorry I have tried with the latest release available from [https://github.com/dcartertod/zotero-plugins/releases](https://github.com/dcartertod/zotero-plugins/releases), i. e. 0.7.0.
After the update to 0.7.8 it works as expected.
