### ISSUE TITLE
In KDE, Zotero window width suddenly expands pushing right side off screen

### ISSUE THREAD

**Issue by jeron1** [dcartertod/zotero-plugins#38]
The issue described below went away when I disabled ZoteroPreview.

Launch Zotero. Zotero maximizes within in the screen, showing collections pane and items pane. The window frame of Zotero is within the viewable area of the screen (e.g., minimize maximize & close icons are visible in upper right hand corner, and File Edit View Tools Help are visible in upper left). I click on an item, expand it to reveal a pdf attachment, double click the pdf attachment, and the attachment opens in a separate smaller pdf window. So far so good. However, if I make a highlight on the pdf, I see the Zotero window in the background suddenly expand in width, so the right side has moved off screen. The window becomes so wide that it actually takes a long time to move it across the screen to the left (with the left side going off the screen) in order to get to the right side so that the minimize and maximize buttons on the upper right become visible. Clicking on maximize does not cause Zotero to fill the screen, rather the width continues to extend off screen where it is not visible. Using key commands (meta + arrow) does snap Zotero to a part of the screen, but the width still extends off screen, so can't see right side. The only way to reduce the width, is to quit and relaunch. However, the issue promptly returns.

I am using Zotero 7.0.3, with Better BibTex 6.7.255, on desktop pc with Kubuntu 24.04 x11. The error occurred when using 1 monitor (as well as 4 monitors). It also occurred when Better BibTex was disabled and when enabled. I also had the same error with Zotero 7.0.1 & 7.0.3 on a Lenovo L380 yoga laptop with Debian 12 KDE 5.27.5 x11. (On the laptop, I had Zotero set to open pdfs in new tabs not windows, but when a pdf opened to a new tab, the whole Zotero window suddenly extended off the right side of the screen.) 

The issue occurred when I used custom CSL as well as a standard one, APA.

I don't have the issue with other apps, e.g., Firefox, Betterbird, Virtualbox, obsidian, Vivaldi, Libreoffice, Crossover by Codeweavers, etc.

Note that I also setup a Linux Mint Xfce pc to test Zotero with ZoteroPreview, and I did NOT have any of the issues described above. Compared to the 2 test PCs above, this Xfce pc had an older type resolution monitor (1200x1600), and very few apps installed on it. 

So, in this limited test, 2 versions of KDE have the issue and one version of Xfce does not.

**Comment by dcartertod** [comment]
Thank you for the detailed report. This will probably be difficult to identify.

**Comment by dcartertod** [comment]
Does the behavior change if you change the relative position of the preview? i.e. the default is at the top, but the prefs allow you to put it after the Info section or at the bottom.

**Comment by dcartertod** [comment]
If you right-click on the header, there's a native feature to view the Bibliographic entry.

**Comment by jeron1** [comment]
I have upgraded Zotero from 7.0.3, and the issue appears to have gone away. I am now using Zotero 7.0.5 on Kubuntu and Debian KDE without the issue. I can't be certain if the Zotero update fixed the issue, but it does seem that some people were having window size issues unrelated to ZoteroPreview (e.g., https://forums.zotero.org/discussion/comment/473701#Comment_473701) that were possibly addressed in the Zotero update 7.0.4 (https://www.zotero.org/support/changelog). 
Many thanks for your work on this valuable plugin.

**Comment by dcartertod** [comment]
Thanks for the update! :-)
