### ISSUE TITLE
Problem on my Mac

### ISSUE THREAD

**Issue by frenchps49** [dcartertod/zotero-plugins#41]
MacOs Ventura 13.7
Zotero 7 version 7.0.6
Zoteropreview shows only in-text Citation
When I choose Bibliography only Preview is empty, no bibliography appears. Thanks for the plugin and for a solution.

**Comment by dcartertod** [comment]
Which version are you running? Can you check for updates?

**Comment by dcartertod** [comment]
Of the plugin that is.

**Comment by frenchps49** [comment]
Thanks for answering. I use ZoteroPreview7 v. 0.7.0


Envoyé depuis Yahoo Mail pour iPhone


Le dimanche, septembre 29, 2024, 1:37 AM, David Tod ***@***.***> a écrit :




Of the plugin that is.

**Comment by dcartertod** [comment]
Check for updates on plugins. Latest should be 0.7.8. I need to made that a release, I guess.

**Comment by frenchps49** [comment]
0.7.8 installed. No change. Still doesn't work. Sorry.

**Comment by dcartertod** [comment]
Would you mind sharing a screenshot of the problem, as well as of your settings?

I'm not sure if I just didn't notice this or if it's been recently added, but there is a native built-in feature to display the Bibliography entry.

![image](https://github.com/user-attachments/assets/c8ab9abf-51d4-4aba-90f3-4c3b74d9840e)

**Comment by dcartertod** [comment]
In May 2024, https://github.com/zotero/zotero/pull/3791 (for my own reference)

**Comment by frenchps49** [comment]
Here are 2 screen captures. Right clicking on the top title "view as bibliography entry" doesn't work either.
![Capture d’écran 2024-09-29 à 17 06 28](https://github.com/user-attachments/assets/aea22e46-81bf-4de1-b5c6-f040d3fdbe7d)
![Capture d’écran 2024-09-29 à 17 06 47](https://github.com/user-attachments/assets/fc87d152-fac5-4233-88f6-a2d369b3ff1b)

**Comment by frenchps49** [comment]
Managed to make it work by clicking on the top title. I had to change a preference. So this closes my issue. Thanks

**Comment by dcartertod** [comment]
Excellent!
