### ISSUE TITLE
Abstract cleaner suggestions: Add instructions and right-click on Abstract itself

### ISSUE THREAD

**Issue by cobblepot1** [dcartertod/zotero-plugins#5]
The abstract cleaner works well! I think it would make more sense to have the option not in the item right-click menu, but in the item info pane when right-clicking on the abstract itself, much like Zotero has the change case options that appear when right-clicking the item title in the info pane. Also, maybe put instructions in the add-on text in Zotero so people who download it without reading the GitHub readme carefully (like me) can figure out how to use it from within Zotero.

**Comment by dcartertod** [comment]
Thank you. 

Good suggestion. Quite difficult, I think. Personally, I wish it was the other way round and I could fix titles across multiple items at one time. Will put this on my list to investigate though. 

For my own reference, textTransform in itembox.xml is a place to start.

**Comment by dcartertod** [comment]
Added instructions to the main description. Not able to work out how to do the contextual menu.
