### ISSUE TITLE
style selection window issues

### ISSUE THREAD

**Issue by kerim** [dcartertod/zotero-plugins#6]
When I installed this the window to select a citations style was initially blank. I hit "esc" and it went away, then reopened. This time I could pick a style, but there was no button to close the window. Nor did clicking outside the box make it go away. I hit "esc." again but it kept coming back. Finally got it to work by restarting the app a few times... Also don't see a way to invoke the window again if I want to change the style later on? 

(Love this by the way - I wish it was a built-in feature of Zotero!)

**Comment by dcartertod** [comment]
Thank you.

My guess is that this has something to do with resolution and screen size. Including an image that shows where the style chooser is - bottom left of the Preview tab.

![image](https://user-images.githubusercontent.com/27686532/122813430-f01d8980-d2a0-11eb-8f6e-e518ae8e1a60.png)

**Comment by jimwillshire** [comment]
Hi,

I'm having this issue too - MacBook Pro 13" 2021 model - any thoughts as I could really do with the preview pane!

Jim

**Comment by dcartertod** [comment]
Screenshot would be helpful.

**Comment by jimwillshire** [comment]
Screenshot below:

<img width="1421" alt="Screenshot 2021-08-13 at 22 29 05" src="https://user-images.githubusercontent.com/88906679/129420272-1627b80b-c391-4158-b4a8-a92ff836850f.png">

**Comment by dcartertod** [comment]
Please check for updates and see if the new version does the trick. Hard
for me to test.

**Comment by jimwillshire** [comment]
No updates available currently...

**Comment by dcartertod** [comment]
What version do you have? I hadn't worked out auto-updating in earlier
versions, so perhaps download this one:
https://github.com/dcartertod/zotero-plugins/raw/main/ZoteroPreview.xpi

Thanks

**Comment by jimwillshire** [comment]
Morning, I've just removed the old version I had, and have installed 2.0 (from your link) and unfortunately still the same behaviour. 

Is there supposed to be a button to confirm the selection?

**Comment by dcartertod** [comment]
I appreciate the update. I don't have access to OSX so this is difficult
for me to troubleshoot. I do have another idea I can try.

**Comment by timjore** [comment]
This is still a problem with the latest version downloaded from the website.

**Comment by jimwillshire** [comment]
Hi @timjore - I've just updated and unfortunately it is still an issue

**Comment by dcartertod** [comment]
Is there a similar tool or function in Zotero or another add-on that pops-up a window like this (that does not have this problem)? I can review their code to see what they're doing.

**Comment by dcartertod** [comment]
Okay...just did a release (I think--github is still a bit of a mystery to me) that might help. I just can't test without a Mac though.

**Comment by jimwillshire** [comment]
Hi, thanks for the update - no change I'm afraid

**Comment by dcartertod** [comment]
New version for Zotero 7 uses the application settings box.
