### ISSUE TITLE
No option to fix abstracts on right click

### ISSUE THREAD

**Issue by ryadaj** [dcartertod/zotero-plugins#7]
High there. Have installed the plugin and restarted Zotero but the option to fix abstracts is not visible when I right click an item.

Thanks for this great tool!

**Comment by dcartertod** [comment]
I clearly messed something up in the most recent release. Will look into it!

**Comment by dcartertod** [comment]
Try this older version: https://github.com/dcartertod/zotero-plugins/blob/31f92027013f688e6ba2eb3d56faf2938e6db791/ZoteroAbstractCleaner.xpi

**Comment by dcartertod** [comment]
Fixed the core issue.
