### ISSUE TITLE
Preview Pane does not automatically refresh on new selection

### ISSUE THREAD

**Issue by SamuelMiller** [dcartertod/zotero-plugins#8]
In the Zotero Beta 5.0.97-beta.46+4cfa23050, the preview pane does not change when selecting a different citation in the Title column. The Preview stays on the same citation, regardless of what other citation one clicks on, until one clicks on and off the Preview pane by selecting another pane such as Notes and the Preview pane again. It would be great if the Preview pane remained linked to the highlighted citation. Thanks.

**Comment by dcartertod** [comment]
Not even sure I knew there was a new version coming. I've not looked at that.

**Comment by dcartertod** [comment]
I'm running 5.0.96.3 (without issues). Not entirely sure how I'd test and install both.

**Comment by dcartertod** [comment]
Released a version to fix this issue. Works in 6.0 too.

**Comment by dcartertod** [comment]
It's not great in 5.x versions, but 6.0 is good.

**Comment by dcartertod** [comment]
Closing this as resolved in Zotero version 6.
